function t(a){this.onready=this.onfail=this.onsuccess=this.suppressAlert=this.password=this.user=this.async=this.url=this.postData=this.method=null;this.headers={};this.params=null;this.sendAsBinary=true;var b=null,c=null,d=null,e=null,g=typeof pui!="undefined"&&typeof pui.alert!="undefined"?pui.alert:alert,f=this;if(typeof a=="object")for(var h in a){if(typeof this[h]!="undefined")this[h]=a[h]}else this.url=a;if(window.XMLHttpRequest)b=new XMLHttpRequest;else if(window.ActiveXObject)b=new ActiveXObject("Microsoft.XMLHTTP");
else{g("Ajax request error: Unsupported browser.");return}this.send=this.send=function(){function i(){if(b.readyState==4){c=b.status+" - "+b.statusText;f.onready!=null&&f.onready(f);if(b.status==200){d=true;f.onsuccess!=null&&f.onsuccess(f)}else{d=false;f.suppressAlert!=true&&g(c);f.onfail!=null&&f.onfail(f)}e=false}}var k=null,l=null,j=null;if(f.method==null)k="GET";else if(typeof f.method!="string"&&(f.method.toUpperCase()!="GET"||f.method.toUpperCase()!="POST"||f.method.toUpperCase()!="PUT")){g('Invalid value for property: "method".');
return}else k=f.method.toUpperCase();if(k=="POST")if(f.postData!=null)if(typeof f.postData!="string"){g('Invalid value for property: "postData".');return}else j=f.postData;else j="";if(f.async==null)l=true;else if(f.async!=true&&f.async!=false){g('Invalid value for property: "async".');return}else l=f.async;if(typeof f.url!="string")g('Invalid value for property: "url".');else{if(f.user!=null)if(typeof f.user!="string"){g('Invalid value for property: "user".');return}if(f.password!=null)if(typeof f.password!=
"string"){g('Invalid value for property: "password".');return}if(f.onsuccess!=null)if(typeof f.onsuccess!="function"){g('Invalid value for event: "onsuccess".');return}if(f.onfail!=null)if(typeof f.onfail!="function"){g('Invalid value for event: "onfail".');return}if(f.onready!=null)if(typeof f.onready!="function"){g('Invalid value for event: "onready".');return}var p=f.url,m=f.params;if(typeof m=="object"){var r="";for(var n in m){var o=m[n],q=[];if(typeof o=="object"){if(o.length!=null&&o.length>
0)q=o}else q.push(o);for(o=0;o<q.length;o++){if(r!="")r+="&";r+=encodeURIComponent(n)+"="+encodeURIComponent(q[o])}}if(r!="")if(k.toUpperCase()=="POST"){if(j!=null&&j!="")j+="&";else j="";j+=r}else{m=p.split("?");if(m.length==2&&m[1]!="")p=m[0]+"?"+m[1]+"&"+r;else p+="?"+r}}try{b.open(k,p,l,f.user,f.password);p=false;var s=f.headers;for(n in s){b.setRequestHeader(n,s[n]);if(n.toUpperCase()=="CONTENT-TYPE")p=true}if(k=="POST")p?b.setRequestHeader("Content-Length",j!=null?j.length:0):b.setRequestHeader("Content-type",
"application/x-www-form-urlencoded")}catch(x){g(x);return}e=true;if(l==true)b.onreadystatechange=i;if(f.sendAsBinary==true)try{b.sendAsBinary(j)}catch(B){b.send(j)}else b.send(j);l!=true&&i()}};this.ok=this.I=function(){return d!=null?d:false};this.getResponseText=this.d=function(){return b.responseText};this.getResponseXML=this.t=function(){return b.responseXML};this.getStatus=this.c=function(){return b.status};this.getStatusText=this.k=function(){return b.statusText};this.getStatusMessage=this.u=
function(){return c};this.getAllResponseHeaders=this.getAllResponseHeaders=function(){if(d)try{return b.getAllResponseHeaders()}catch(i){g(i)}};this.getResponseHeader=this.getResponseHeader=function(i){if(d)try{return b.getResponseHeader(i)}catch(k){g(k)}};this.setRequestHeader=this.setRequestHeader=function(i,k){f.headers[i]=k};this.abort=this.abort=function(){if(!(e==null||e==true))try{b.abort()}catch(i){g(i)}}}
function u(a,b){var c,d,e,g="";if(arguments.length==1&&typeof arguments[0]=="object"){c=arguments[0];c.async=null;c.onsuccess=null;if(typeof c.handler=="function"){d=true;e=c.handler}else d=false}else if(b!=null&&typeof b=="function"){d=true;e=b}else d=false;c=new t(arguments[0]);c.async=d;c.onsuccess=function(f){g+=f.d();d==true&&e(g)};c.send();if(d==false)return g}if(typeof window.pui=="undefined")window.pui={};window.RPGspRequest=t;window.pui.Ajax=t;window.pui.AjaxRequest=t;window.ajax=u;
window.ajaxXML=function(a,b){var c,d,e,g=null;if(arguments.length==1&&typeof arguments[0]=="object"){c=arguments[0];c.async=null;c.onsuccess=null;c.onfail=null;c.onsuccess=null;if(typeof c.handler=="function"){d=true;e=c.handler}else d=false}else if(b!=null&&typeof b=="function"){d=true;e=b}else d=false;c=new t(arguments[0]);c.async=d;c.onsuccess=function(f){g=f.t();d==true&&e(g)};c.send();if(d==false)return g};
window.ajaxJSON=function(a,b){var c,d,e,g=null,f=false;if(arguments.length==1&&typeof arguments[0]=="object"){c=arguments[0];c.async=null;c.onsuccess=null;if(c.saveResponse==true)f=true;if(typeof c.handler=="function"){d=true;e=c.handler}else d=false}else if(b!=null&&typeof b=="function"){d=true;e=b}else d=false;c=new t(arguments[0]);c.async=d;c.onsuccess=function(h){h=h.d();if(f&&typeof pui=="object")pui.savedJSON=h;try{g=eval("("+h+")")}catch(i){e(null,i);return}d==true&&e(g)};c.send();if(d==false)return g};
window.ajaxSubmit=function(a,b){var c,d="",e=typeof pui!="undefined"&&typeof pui.alert!="undefined"?pui.alert:alert;if(typeof a=="object")c=a;else{c=document.getElementById(a);if(c==null)c=document.forms[a]}var g;if(c!=null)g=c.tagName;if(c==null||g==null||g.toUpperCase()!="FORM"){e("Ajax request error: Invalid form object.");return""}if(a.action==""){e("Ajax request error: Invalid form action.");return""}for(e=0;e<c.elements.length;e++){g=c.elements[e];if(g.name!=null&&g.name!=""){var f=false;if(g.tagName==
"INPUT"){var h=g.type;h=h.toLowerCase();if(h=="hidden")f=true;if(h=="password")f=true;if(h=="text")f=true;if(pui.ia(h))f=true;if(h=="")f=true;if(h=="checkbox"||h=="radio")if(g.checked)f=true}if(g.tagName=="TEXTAREA")f=true;if(g.tagName=="SELECT")f=true;if(f){if(d!="")d+="&";d+=g.name+"="+encodeURIComponent(g.value)}}}c=new t(c.action);c.method="POST";c.postData=d;var i="",k;if(b!=null&&typeof b=="function")k=true;else{k=false;c.async=false}c.onsuccess=function(l){i+=l.d();k==true&&b(i)};c.send();
if(k==false)return i};function v(a){var b;a=a!=null&&typeof a=="object"?a:document.getElementById(a);if(a==null)return"";b="";if(a.tagName.toLowerCase()=="div"){b=a.firstChild;b=b!=null&&b.tagName!=null&&b.tagName=="A"?b.innerHTML:a.innerHTML}if(a.tagName=="INPUT"&&a.type=="checkbox"){if(a.checked&&a.h!=null)return a.h;if(!a.checked&&a.Q!=null)return a.Q;return a.checked}if(a.tagName=="INPUT"||a.tagName=="TEXTAREA")b=a.value;if(a.tagName=="SELECT"){b=a.selectedIndex;b=b>=0?a.options[b].value:a.pui&&a.pui.properties&&a.pui.properties.value?
a.pui.properties.value:a.value}if(a.comboBoxWidget!=null)b=a.comboBoxWidget.getValue();if(a.v!=null)b=String(a.value);if(a.e!=null){b="";if(a.e.F&&a.e.J!=null)b=a.e.J;else if(!a.e.F&&a.e.H!=null)b=a.e.H}for(b=b.replace(/&nbsp;/g," ");b.indexOf(String.fromCharCode(160))!=-1;)b=b.replace(String.fromCharCode(160)," ");if(b==a.ba)b="";return b}function w(a){return a.replace(/^\s*|\s*$/g,"")}pui.detachCalendar=function(a){if(typeof a=="string")a=document.getElementById(a);a!=null&&pui.ma(a)};
function y(a,b,c){var d=false,e=location.href;e=e.split("?")[0];e=e.split("/");if(e.length>2&&e[e.length-2].toLowerCase()=="auth")d=true;e="/profoundui/";if(d==true||c==true)e+="auth/";e+=a;if(b!=null&&b==true)e+="/"+PSID;if(pui.serverURL!=null)e=pui.serverURL+e;return e}pui.getProgramURL=y;pui.da=function(a){return pui.s(a).x};pui.ea=function(a){return pui.s(a).y};
pui.s=function(a){a=a||window.event;var b={x:0,y:0};if(a!=null&&a.touches!=null&&a.touches.length==1){b.x=a.touches[0].pageX;b.y=a.touches[0].pageY}else if(a!=null){if(a.pageX)b.x=a.pageX;else if(a.clientX)b.x=a.clientX+(document.documentElement.scrollLeft?document.documentElement.scrollLeft:document.body.scrollLeft);if(a.pageY)b.y=a.pageY;else if(a.clientY)b.y=a.clientY+(document.documentElement.scrollTop?document.documentElement.scrollTop:document.body.scrollTop)}return b};
function z(){var a={},b="";b=location.search.substring(1,location.search.length);if(b.length==0)return a;b=b.replace(/\+/g," ");b=b.split("&");for(var c=0;c<b.length;c++){var d=b[c].split("="),e=decodeURIComponent(d[0]),g="";if(d.length==2)g=decodeURIComponent(d[1]);a[e]=g}return a}if(typeof applyDesignProperty!="undefined")window.T=applyDesignProperty;
pui.o={r:function(a){for(var b="",c=0;c<a.length;c++){var d=a.charCodeAt(c);if(d<128)b+=String.fromCharCode(d);else{if(d>127&&d<2048)b+=String.fromCharCode(d>>6|192);else{b+=String.fromCharCode(d>>12|224);b+=String.fromCharCode(d>>6&63|128)}b+=String.fromCharCode(d&63|128)}}return b},q:function(a){for(var b="",c=0,d=c1=c2=0;c<a.length;){d=a.charCodeAt(c);if(d<128){b+=String.fromCharCode(d);c++}else if(d>191&&d<224){c2=a.charCodeAt(c+1);b+=String.fromCharCode((d&31)<<6|c2&63);c+=2}else{c2=a.charCodeAt(c+
1);c3=a.charCodeAt(c+2);b+=String.fromCharCode((d&15)<<12|(c2&63)<<6|c3&63);c+=3}}return b}};
pui.S={b:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",r:function(a){var b="",c,d,e,g,f,h,i=0;for(a=pui.o.r(a);i<a.length;){c=a.charCodeAt(i++);d=a.charCodeAt(i++);e=a.charCodeAt(i++);g=c>>2;c=(c&3)<<4|d>>4;f=(d&15)<<2|e>>6;h=e&63;if(isNaN(d))f=h=64;else if(isNaN(e))h=64;b=b+this.b.charAt(g)+this.b.charAt(c)+this.b.charAt(f)+this.b.charAt(h)}return b},q:function(a){var b="",c,d,e,g,f,h=0;for(a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");h<a.length;){c=this.b.indexOf(a.charAt(h++));d=
this.b.indexOf(a.charAt(h++));g=this.b.indexOf(a.charAt(h++));f=this.b.indexOf(a.charAt(h++));c=c<<2|d>>4;d=(d&15)<<4|g>>2;e=(g&3)<<6|f;b+=String.fromCharCode(c);if(g!=64)b+=String.fromCharCode(d);if(f!=64)b+=String.fromCharCode(e)}return b=pui.o.q(b)}};
pui.downloadJSON=function(){if(pui.savedJSON==null)pui.alert("JSON is not available.");else{var a=pui.savedJSON;if(typeof JSON==="object"&&typeof JSON.parse==="function"&&typeof JSON.stringify==="function")try{a=JSON.stringify(JSON.parse(pui.savedJSON),null,"  ")}catch(b){}pui.aa("text/plain","json.txt",a)}};
pui.keepAlive=function(){var a;if(!(context=="genie"&&pui.f.g==true)){if(context=="dspf")a=pui.f==null?y("PUI0001200.pgm"):y("PUI0002110.pgm");else if(context=="genie")a=DOCUMENT_URI;else return false;if(pui.psid!=null&&pui.psid!="")a+="/"+pui.psid;if(pui.overrideSubmitUrl!=null&&typeof pui.overrideSubmitUrl=="function")try{a=pui.overrideSubmitUrl(a)}catch(b){}if(context=="genie")pui.w(pui.f.g=true);if(context=="dspf")pui.n=false;pui.oa();u({url:a,method:"post",params:{keepalive:"1"},sendAsBinary:false,
suppressAlert:true,handler:function(){pui.C();if(context=="genie")pui.w(pui.f.g=false);if(context=="dspf"){pui.n=true;for(var c=0;c<pui.l.length;c++)pui.l[c].P()}},onfail:function(c){pui.onoffline==null&&!pui["suppress comm errors"]&&pui.alert(pui.fa(c));pui.C();if(context=="genie")pui.w(pui.f.g=false);if(context=="dspf"){pui.n=true;for(c=0;c<pui.l.length;c++)pui.l[c].P()}pui.onoffline!=null&&pui.onoffline()}});return true}};
pui.getWindowSize=function(){var a,b;if(document.body&&document.body.offsetWidth){a=document.body.offsetWidth;b=document.body.offsetHeight}if(document.compatMode=="CSS1Compat"&&document.documentElement&&document.documentElement.offsetWidth){a=document.documentElement.offsetWidth;b=document.documentElement.offsetHeight}if(window.innerWidth&&window.innerHeight){a=window.innerWidth;b=window.innerHeight}if(a==null&&screen!=null)a=screen.width;if(b==null&&screen!=null)b=screen.height;if(a==null)a=800;
if(b==null)b=600;return{width:a,height:b}};pui.openURL=function(a){window.open(a)};pui.normalizeURL=function(a,b){if(a==null||typeof a!="string")return"";if(b==true&&window.puiMobileClient==null)return a;if(a.substr(0,5).toLowerCase()=="http:"||a.substr(0,6).toLowerCase()=="https:")return a;return pui.serverURL!=null?pui.serverURL+a:window.cordova&&a.substr(0,1)=="/"?a.substr(1):a};
pui.animate=function(a){var b=a.element;if(typeof b=="string")b=document.getElementById(b);if(b!=null){var c,d=a.effect;if(d=="fly in left"||d=="fly in right"||d=="fly out left"||d=="fly out right")c="left";else if(d=="fly in up"||d=="fly in down"||d=="fly out up"||d=="fly out down")c="top";else if(d=="fade in"||d=="fade out")c="opacity";else{c=a.properties;if(c==null){c=a.property;if(c==null)return}}if(typeof c=="string")c=[c];var e=a.duration;if(e==null)e="500ms";if(e.substr(e.length-1,1)!="s")e+=
"s";var g=parseInt(e)*1E3;if(e.length>2&&e.substr(e.length-2,2)=="ms")g=parseInt(e);var f=a.type;if(f==null)f="ease";var h=a.from,i=a.to;switch(d){case "fly in right":h=-b.offsetWidth;h+="px";i="0px";break;case "fly in left":h=b.offsetWidth;h+="px";i="0px";break;case "fly out left":i=-b.offsetWidth;i+="px";h="0px";break;case "fly out right":i=b.offsetWidth;i+="px";h="0px";break;case "fly out down":i=b.offsetHeight;i+="px";h="0px";break;case "fly out up":i=-b.offsetHeight;i+="px";h="0px";break;case "fly in up":h=
b.offsetHeight;h+="px";i="0px";break;case "fly in down":h=-b.offsetHeight;h+="px";i="0px";break;case "fade in":h="0";i="100";break;case "fade out":h="100";i="0";break}if(i!=null){var k="";for(d=0;d<c.length;d++){var l=c[d];if(k!="")k+=", ";k+=l+" "+e+" "+f}var j=["transition","MozTransition","WebkitTransition","msTransition","OTransition"];if(h!=null){if(typeof h=="string"||typeof h=="number")h=[h];for(d=0;d<c.length;d++){l=c[d];b.style[l]=h[d]}}setTimeout(function(){for(var p=0;p<j.length;p++)b.style[j[p]]=
k;setTimeout(function(){if(typeof i=="string"||typeof i=="number")i=[i];for(var m=0;m<c.length;m++)b.style[c[m]]=i[m];setTimeout(function(){for(var r=0;r<j.length;r++)b.style[j[r]]="";a.oncomplete!=null&&a.oncomplete()},g)},1)},1)}}};pui.getActiveElement=function(){return context=="genie"?lastActiveElement:pui.activeElement};pui.fieldExit=function(a){var b=pui.getActiveElement();if(b!=null){var c=false;if(a!=null)c=true;context=="genie"?fieldExit(b,c):pui.Y(b)}};
pui.showCalendar=function(a){var b=a;if(typeof a=="string")b=document.getElementById(a);if(b!=null)if(typeof b=="object"){var c=b.calimg;if(c!=null)if(c.click!=null&&typeof c.click=="function")c.click();else c.onclick!=null&&typeof c.onclick=="function"&&setTimeout(function(){c.onclick()},250)}};pui.getComputedStyle=function(a){var b=null;if(window.getComputedStyle)b=window.getComputedStyle(a);else if(a.currentStyle)b=a.currentStyle;return b};
pui.upload=function(a,b){var c=a.dir,d=a.overwrite===true,e;if(typeof a.slimit=="number")e=a.slimit;var g;if(typeof a.flimit=="number")g=a.flimit;var f="";if(typeof a.altname=="string")f=a.altname;var h;if(typeof a.allowedTypes&&a.allowedTypes instanceof Array)h=a.allowedTypes;if(g==null)g=a.files.length;if(e==null||h==null){for(var i,k=[],l=0;l<a.files.length;l++){var j=a.files[l],p=typeof j.type!="undefined"&&j.type!=""?j.type:"application/octet-stream";pui.U(k,p)==-1&&k.push(p);j=j.data&&j.data instanceof
ArrayBuffer?j.data.byteLength:j.size;j=Math.ceil(j/1048576);if(i==null||j>i)i=j}if(e==null)e=i;if(h==null)h=k}i=y("PUI0009109.PGM");i+="?AUTH="+encodeURIComponent(pui.appJob.auth);i+="&mode=ajax";i+="&r="+Math.floor(Math.random()*1E9);k=new FormData;k.append("dir",c);k.append("overwrite",d?"1":"0");k.append("flimit",g);k.append("slimit",e);k.append("altname",f);for(l=0;l<h.length;l++)k.append("type",h[l]);for(l=0;l<a.files.length;l++){j=a.files[l];if(j.data&&j.data instanceof ArrayBuffer){var m;try{m=
new Blob([j.data])}catch(r){c=new window.WebKitBlobBuilder;c.append(j.data);m=c.getBlob()}k.append("file",m)}else k.append("file",j);k.append("filename",j.name)}var n=new XMLHttpRequest;n.open("POST",i,true);n.onreadystatechange=function(){if(n.readyState==4){var o=true,q;if(n.status==200){var s;try{s=eval("("+n.responseText+")")}catch(x){o=false;q="Server response missing or invalid."}if(s){o=s.success;if(!o)if(s.key){q=pui.getLanguageText("runtimeMsg","upload "+s.key);if(s.key=="file limit")q=q.replace("&1",
g);if(s.key=="size limit")q=q.replace("&1",e)}else q=s.error}}else{o=false;q=n.status+" - "+n.statusText+"."}typeof b=="function"&&b(o,q)}};n.send(k)};pui.getCookie=function(a){var b=document.cookie.split(";"),c="",d="",e="",g="";for(g=0;g<b.length;g++){c=b[g].split("=");d=c[0].replace(/^\s+|\s+$/g,"");if(d==a){if(c.length>1)e=unescape(c[1].replace(/^\s+|\s+$/g,""));return e}}return null};
pui.setCookie=function(a,b,c,d,e,g){var f=new Date;f.setTime(f.getTime());if(c)c=c*1E3*60*60*24;f=new Date(f.getTime()+c);document.cookie=a+"="+escape(b)+(c?";expires="+f.toGMTString():"")+(d?";path="+d:"")+(e?";domain="+e:"")+(g?";secure":"")};pui.deleteCookie=function(a,b,c){if(pui.getCookie(a))document.cookie=a+"="+(b?";path="+b:"")+(c?";domain="+c:"")+";expires=Thu, 01-Jan-1970 00:00:01 GMT"};
pui.refresh=function(a){if(a==null)a={};var b=a.url;a=a.skin;pui.setCookie("puiRefreshId",pui.psid,null,"/");pui.skipConfirm=true;pui.shutdownOnClose=false;pui.confirmOnClose=false;if(a!=null){a="skin="+encodeURIComponent(a);b=window.location.href;var c=b.split("?");b=c[0];c=c[1];if(c==null)c="";qparms=c.split("&");c=false;for(var d=0;d<qparms.length;d++)if(qparms[d].length>=5&&qparms[d].substr(0,5).toLowerCase()=="skin="){qparms[d]=a;c=true}if(!c)if(qparms.length==1&&qparms[0]=="")qparms[0]=a;else qparms.push(a);
c=qparms.join("&");b=b+"?"+c}if(b!=null)window.location.href=b;else window.location.reload()};
pui.downloadURL=function(a){if(pui==null||pui.appJob==null||pui.appJob.auth==null||pui.appJob.auth=="")return pui.is_ie?"":"data:text/html,<!DOCTYPE html><html><body><p>To download, please connect to a Profound UI session.</p></body></html>";var b=a.inline===true;if(a.id==null)return"";var c=y("PUI0009110.PGM");c+="?id="+encodeURIComponent(a.id);if(a.contentType!=null)c+="&type="+encodeURIComponent(a.contentType);if(b)c+="&inline=1";c+="&usehttprc=0";c+="&AUTH="+encodeURIComponent(pui.appJob.auth);
c+="&r="+Math.floor(Math.random()*1E9);return c};pui.download=function(a){var b=pui.downloadURL(a);a=a.inline===true;if(pui==null||pui.appJob==null||pui.appJob.auth==null||pui.appJob.auth=="")a=true;a?pui.openURL(b):pui.link(b)};
pui.focusOnContainer=function(){setTimeout(function(){if(pui.a==null){pui.a=document.createElement("input");pui.a.type=pui.is_touch?"button":"text";pui.a.readOnly=true;pui.a.style.position="absolute";pui.a.style.left="-999px";pui.a.style.top="-999px";pui.a.style.width="10px";pui.a.style.borderStyle="none";pui.a.style.backgroundColor="transparent";pui.runtimeContainer.appendChild(pui.a)}pui.D=true;pui.a.focus();setTimeout(function(){pui.D=false},0)},1)};
pui.addCSS=function(a){var b=document.getElementsByTagName("head")[0],c=document.createElement("style");c.type="text/css";if(pui.is_old_ie)c.styleSheet.cssText=a;else c.innerHTML=a;b.appendChild(c)};pui.loadCSS=function(a){if(pui.B(a)!=null)return false;var b=document.getElementsByTagName("head")[0],c=document.createElement("link");c.setAttribute("rel","stylesheet");c.setAttribute("type","text/css");c.setAttribute("media","screen");c.setAttribute("href",pui.normalizeURL(a));b.appendChild(c);return true};
pui.removeCSS=function(a){var b=document.getElementsByTagName("head")[0],c=pui.B(a);if(c==null){c=b.getElementsByTagName("style");for(var d=0;d<c.length;d++){var e=c[d];if(e.innerHTML==a||e.styleSheet!=null&&e.styleSheet.cssText==a){b.removeChild(e);return true}}return false}else{b.removeChild(c);return true}};
pui.loadJS=function(a){if(a==null)return null;var b,c,d,e;if(typeof a=="string")b=a;if(typeof a=="object"){b=a.path;c=a.callback;d=a.onerror;e=a.test;if(e!=null&&typeof e=="function"&&e()==true)return false}if(b==null)return null;if(pui.ga(pui.normalizeURL(b))!=null)return false;a=document.getElementsByTagName("head")[0];var g=false,f=document.createElement("script");f.type="text/javascript";f.onreadystatechange=function(){if(f.readyState=="complete"||f.readyState=="loaded")if(!(e!=null&&typeof e==
"function"&&e()!=true)){!g&&c!=null&&c();g=true}};f.onload=function(){if(!(e!=null&&typeof e=="function"&&e()!=true)){!g&&c!=null&&c();g=true}};if(d)f.onerror=d;f.src=pui.normalizeURL(b);a.appendChild(f);return true};
pui.endOfSession=function(a){pui.confirmOnClose=false;pui.shutdownOnClose=false;if(window.puiMobileClient!=null&&window.puiMobileClient.showConnections!=null){window.puiMobileClient.showConnections();a!=null&&pui.alert(a)}else{var b=z().gobackto;if(b!=null){document.body.innerHTML="";a!=null&&pui.alert(a);location.href=b}if(navigator.app!=null&&navigator.app.exitApp!=null){document.body.innerHTML="";a!=null?pui.alert(a,function(){navigator.app.exitApp()}):navigator.app.exitApp()}}};
pui.alert=function(a,b,c,d){if(window.navigator!=null&&window.navigator.notification!=null&&window.navigator.notification.alert!=null)if(b==null&&c==null&&d==null&&window.puiMobileClient!=null&&window.puiMobileClient.alert!=null)window.puiMobileClient.alert(a);else{if(b==null)b=function(){};if(c==null)c="Profound UI";if(d==null)d="OK";window.navigator.notification.alert(a,b,c,d)}else alert(a)};pui.get=function(a){return w(v(a))};
pui.set=function(a,b){var c;c=typeof a=="object"?a:document.getElementById(a);if(c!=null){if(c.tagName=="DIV")if(c.v!=null)c.v.setValue(b);else if(c.comboBoxWidget!=null)c.comboBoxWidget.setValue(b);else if(c.button&&c.button.O)c.button.O.innerHTML=b;else c.innerHTML=b;if(c.tagName=="INPUT"||c.tagName=="SELECT"||c.tagName=="TEXTAREA")if(c.tagName=="INPUT"&&c.type=="checkbox")c.checked=typeof b=="boolean"?b:c.h!=null&&b==c.h?true:false;else c.value=b;if(context=="dspf"||pui.R&&c.j==null){c.modified=
true;var d=c.ra;if(c.id!=null&&c.id.indexOf(".")==-1&&c.A!=null)pui.X[c.A]=true;if(d!=null){d.ha();d.Z=true;pui.na(c,d.ca())}}if(context=="genie"&&c.j!=null&&c.j.idx!=null)pui.response[c.j.idx]=c;pui.V(c);if(c.pui&&c.pui.properties)c.pui.properties.value=b}};pui.getActiveContainer=function(){if(context=="genie"){for(var a=1,b=document.getElementById("window"+a);b;){var c=document.getElementById("window"+ ++a);if(c)b=c;else break}if(b)return b}else if(context=="dspf"&&pui.G)return pui.G;return pui.runtimeContainer};
pui.getDisplayType=function(){return pui.R?"5250-handler":context=="dspf"?"rdf":"5250"};
function A(a){function b(){if(!(g>=e.length)){var f=e[g].command,h=e[g].wait;g+=1;if(c>=1){var i=h?"1":"0";i="http://localhost:"+(typeof pui["pc listener port"]=="number"?pui["pc listener port"]:80)+"/?cmd="+encodeURIComponent(f)+"&wait="+i;if(c>=2){i+="&type=image&rnd="+String(Math.random())+String((new Date).getTime());h=new Image;h.onload=function(){b()};h.src=i}else{i=new pui.Ajax(i);i.method="GET";i.async=h?false:true;i.pa=true;i.ja=function(l){if(l.c()!=200){console.log("PC Command Listener comm. failure: "+
l.u());console.log("Command: "+f)}};i.ka=function(){b()};i.send()}}else{if(g==0&&e.length>0){h=[];for(i=0;i<e.length;i++)h.push("("+e[i].W+")");f=h.join(" && ")}try{d.runCommand(f)}catch(k){h='Unable to execute "'+f+'".\n\n';if(k!=null)h+=k.name+":\n\n"+k.message+".";alert(h)}}}}var c=0;if(pui["use pc listener"])c=1;if(window.HTTPS!=null&&window.HTTPS=="ON"&&c==1)c=2;if(pui["pc listener mode"])c=parseInt(pui["pc listener mode"]);if(c==0){var d=document.getElementById("PCCommandApplet");if(!d){pui.p=
a;loadPCCommandApplet("runCommandCb");return}}var e=[],g=0;e=typeof a=="string"?[{command:a,wait:false}]:a;b()}window.runCommandCb=function(){A(pui.p);pui.p=null};pui.runPCCommand=A;
pui.isServerBusy=function(){if(typeof context=="undefined")return false;if(context=="dspf"&&pui.n===false||context=="genie"&&pui.f.g===true)return true;for(var a=document.getElementsByTagName("iframe"),b=0;b<a.length;b++){var c=a[b].contentWindow;if(c!=null){var d=null;try{d=c.pui}catch(e){}if(d!=null)if(typeof d==="object")if(typeof d.isServerBusy==="function")if(d.isServerBusy())return true}}return false};
pui.showLastError=function(){if(errors.length==0)alert("No errors have been reported.");else{var a=errors.length-1;alert("Operation: "+errors[a].la+"\nId: "+errors[a].id+"\n\nMessage: "+errors[a].text+"\n"+errors[a].qa)}};pui.m=navigator.userAgent.indexOf("Safari")!=-1&&navigator.userAgent.indexOf("Chrome")==-1;
pui.N=function(){for(var a=document.getElementById("auth-form"),b=document.cookie.split("; "),c=false,d=0;d<b.length;d++){var e=b[d].split("=");if(unescape(e[0])=="pui-signon-"+a.action)if(unescape(e[1])=="1"){c=true;break}}if(typeof Storage!="undefined"){b=z();if(b.workstnid)sessionStorage["atrium-params-workstnid"]=b.workstnid;else try{delete sessionStorage["atrium-params-workstnid"]}catch(g){}if(b.suffixid)sessionStorage["atrium-params-suffixid"]=b.suffixid;else try{delete sessionStorage["atrium-params-suffixid"]}catch(f){}if(b.duplicateid)sessionStorage["atrium-params-duplicateid"]=
b.duplicateid;else try{delete sessionStorage["atrium-params-duplicateid"]}catch(h){}}if(c)location.href=a.action;else{if(c=document.getElementById("auth-box"))c.style.display="";a.elements["auth-user"].focus()}};
pui.M=function(){var a=document.getElementById("auth-form"),b=a.elements["auth-user"].value,c=a.elements["auth-password"].value,d=document.getElementById("auth-message");d.innerHTML="";if(w(b)==""){d.innerHTML=authMessages["user required"];a.elements["auth-user"].focus();return false}else if(w(c)==""){d.innerHTML=authMessages["password required"];a.elements["auth-password"].focus();return false}pui.i(function(){var e=new pui.Ajax("/profoundui/pui0005010.pgm");e.async=true;e.method="POST";e.user=b;
e.password=c;if(pui.m){e.user=encodeURIComponent(e.user);e.password=encodeURIComponent(e.password)}e.suppressAlert=true;e.onready=function(g){if(g.c()==200){var f=eval("("+g.d()+")");g=f.days;var h=false;if(f.warn==true)if(g==0){f=authMessages["password expired"];pui.alert(f);h=true}else{f=authMessages["password pending expiration"];f=f.replace(/{DAYS}/g,g);h=confirm(f)}if(h){g="/profoundui/changepass";g+="?user="+encodeURIComponent(b);g+="&next="+encodeURIComponent(a.action);g+="&back="+encodeURIComponent(location.href);
location.href=g}else{document.cookie=escape("pui-signon-"+a.action)+"=1; path=/";location.href=a.action}}else{d.innerHTML=authMessages["invalid credentials"];a.elements["auth-user"].focus()}};e.send()});return false};pui.i=function(a){var b=new pui.Ajax("/profoundui/pui0005010.pgm");b.async=true;b.method="POST";b.user=b.password="PUI_SIGNOFF_USER";if(pui.m)b.user=b.password=encodeURIComponent(b.user);b.suppressAlert=true;b.onready=function(){typeof a=="function"&&a()};b.send()};
window.pui.signOn=pui.M;window.pui.clearCredentials=pui.i;window.pui.signOnInit=pui.N;pui.L=function(){var a=z(),b=document.getElementById("change-user"),c=document.getElementById("change-current"),d=b,e=document.getElementById("change-cancel");if(typeof a.user!="undefined"){b.value=a.user.toUpperCase();b.readOnly=true;b.className+=" read-only";d=c}if(typeof a.back=="undefined")e.style.display="none";document.getElementById("change-box").style.display="block";d.focus()};
pui.K=function(){var a=z();if(typeof a.back!="undefined")location.href=a.back};
pui.z=function(){var a=z(),b=document.getElementById("change-form"),c=b.elements["change-user"].value,d=b.elements["change-current"].value,e=b.elements["change-new"].value,g=b.elements["change-confirm"].value,f=document.getElementById("change-message");f.innerHTML="";if(w(c)==""){f.innerHTML=passMessages["user required"];b.elements["change-user"].focus();return false}else if(w(d)==""){f.innerHTML=passMessages["current required"];b.elements["change-current"].focus();return false}else if(w(e)==""){f.innerHTML=
passMessages["new required"];b.elements["change-new"].focus();return false}else if(w(g)==""){f.innerHTML=passMessages["confirm required"];b.elements["change-confirm"].focus();return false}else if(e!=g){f.innerHTML=passMessages["must match"];b.elements["change-new"].focus();return false}g=new pui.Ajax("/profoundui/pui0005011.pgm");g.async=true;g.method="POST";g.params={};g.params.user=c;g.params.current=d;g.params["new"]=e;g.suppressAlert=true;g.onready=function(h){if(h.c()!=200){f.innerHTML="HTTP "+
h.c()+" - "+h.k()+".";b.elements["change-user"].focus()}else{var i;try{i=eval("("+h.d()+")");if(typeof i.success!="boolean")throw"";if(!i.success&&typeof i.error!="string")throw"";}catch(k){i={};i.success=false;i.error="The server response is missing or invalid."}if(i.success==false){f.innerHTML=i.error;b.elements["change-user"].focus()}else{pui.alert(passMessages.success);pui.i(function(){var l=new pui.Ajax("/profoundui/pui0005010.pgm");l.async=true;l.method="POST";l.user=c;l.password=e;if(pui.m){l.user=
encodeURIComponent(l.user);l.password=encodeURIComponent(l.password)}l.suppressAlert=true;l.onready=function(j){if(j.c()==200){if(typeof a.next!="undefined")location.href=a.next}else{pui.alert("HTTP "+j.c()+" - "+j.k()+".");b.elements["change-user"].focus()}};l.send()})}}};g.send();return false};window.pui.passInit=pui.L;window.pui.passCancel=pui.K;window.pui.changePass=pui.z;
